FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3 python3-pip git
RUN pip3 install pika 

ENV RABBITMQ_HOST='172.18.0.1'
EXPOSE 8008

WORKDIR /srv
COPY logs.py /srv
CMD [ "python3", "logs.py"]